/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        calc.getVersion();
        //calc.add1(1, 2);
        calc.add(1, 4);
        calc.subtract(8, 4);
        calc.multiply(7, 3);
        calc.divide(9, 3);

    System.out.println(calc.getResult());

    ScientificCalculator calc1 = new ScientificCalculator();
    double result = calc1.cubeOf(4.0);
    System.out.println(result);

    double result1 = calc1.squareOf(4.0);
    System.out.println(result1);

    double result2 = calc1.powerOf(4.0, 5.0);
    System.out.println(result2);

    double result3 = calc1.squareRoot(6.0);
    System.out.println(result3
    
    );



 
 
    }
}
